SPACE = 'space'
COMMENT = 'comment'

PLUS_ASSIGN = 'plus_assign'
PLUS = 'plus'
MOD_ASSIGN = 'mod_assign'
MOD = 'mod'
DIVISION_ASSIGN = 'div_assign'
DIVISION = 'div'
POW = 'pow'
MULT_ASSIGN = 'mult_assign'
MULT = 'mult'

NOT = 'not'
AND = 'and'
OR = 'or'
XOR = 'xor'
GREATER_EQUAL = 'greater_eq'
GREATER = 'greater'
LESS_EQUAL = 'less_eq'
LESS = 'less'
EQUAL = 'eq'
ASSIGN = 'assign'
NOT_EQUAL = 'not_eq'

BRACKET_OPEN = 'bracket_open'
BRACKET_CLOSE = 'bracket_close'
CURLY_BRACKET_OPEN = 'curly_bracket_open'
CURLY_BRACKET_CLOSE = 'curly_bracket_close'
SEMICOLON = 'semicolon'
CONCAT = 'concat'

ADD = 'add'
IF = 'if'
ELSE = 'else'
WHILE ='while'
PRINT = 'print'
INPUT = 'input'
BOOL = 'bool'
STRING = 'string'
MINUS_ASSIGN = 'minus_assign'
FLOAT = 'float'
INT = 'int'
MINUS = 'minus'
VARIABLE = 'var'
